site_name: "E-Wood"
site_description: "Estimating"
theme:
  name: material
  language: ru
  palette:
    - scheme: slate
      primary: green
      accent: light green
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - content.code.copy
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Work:
      - Vertical Constructions:
          - Walls:
              - ‚óºÔ∏è Sill Plates: work/vertical/walls/sill-plates.md
              - ‚óºÔ∏è Unit: work/vertical/walls/unit.md
              - ‚óºÔ∏è Exterior: work/vertical/walls/exterior.md
              - ‚óºÔ∏è Corridor: work/vertical/walls/corridor.md
              - ‚óºÔ∏è Demising: work/vertical/walls/demising.md
              - ‚óºÔ∏è Gable: work/vertical/walls/gable.md
              - ‚óºÔ∏è Parapet: work/vertical/walls/parapet.md
              - ‚óºÔ∏è Shaft: work/vertical/walls/shaft.md
              - ‚óºÔ∏è Furring: work/vertical/walls/furring.md
              - ‚óºÔ∏è Corners: work/vertical/walls/corners.md
          - Openings:
              - ‚óºÔ∏è Windows & Doors: work/vertical/openings/windows-doors.md
              - ‚óºÔ∏è Headers: work/vertical/openings/headers.md
          - Sheathing:
              - ‚óºÔ∏è Wall Sheathing: work/vertical/sheathing/wall-sheathing.md
              - ‚óºÔ∏è Floor: work/vertical/sheathing/floor.md
              - ‚óºÔ∏è Gable: work/vertical/sheathing/gable.md
              - ‚óºÔ∏è Duplicate of Gable: work/vertical/sheathing/duplicate-of-gable.md
              - ‚óºÔ∏è Box Sheathing: work/vertical/sheathing/box-sheathing.md
              - ‚óºÔ∏è Truss Heel: work/vertical/sheathing/truss-heel.md
              - ‚óºÔ∏è Shear Wall: work/vertical/sheathing/shear-wall.md
      - SQFT's:
          - ‚óºÔ∏è Basement: work/SQFT's/basement.md
          - ‚óºÔ∏è 1st, 2nd ‚Ä¶.. 5th: work/SQFT's/1st2nd.md
          - ‚óºÔ∏è Loft: work/SQFT's/loft.md
          - ‚óºÔ∏è Roof: work/SQFT's/roof.md
          - ‚óºÔ∏è Deck: work/SQFT's/deck.md
          - ‚óºÔ∏è Porch: work/SQFT's/porch.md
          - ‚óºÔ∏è Balcony: work/SQFT's/balcony.md
          - ‚óºÔ∏è Cantilevered: work/SQFT's/cantilevered.md
      - Sheathing and Misc:
          - ‚óºÔ∏è Eve: work/sheathingandmisc/eve.md
          - ‚óºÔ∏è Rake: work/sheathingandmisc/rake.md
          - ‚óºÔ∏è Returns: work/sheathingandmisc/returns.md
          - ‚óºÔ∏è Roof Asphalt, Metal, Flat: work/sheathingandmisc/rooftype.md
          - ‚óºÔ∏è Ridge , Valley, Hip: work/sheathingandmisc/ridgevalleyhip.md
          - ‚óºÔ∏è Flashing: work/sheathingandmisc/flashing.md
      - Horizontal Constructions:
          - Floor Framing:
              - ‚óºÔ∏è Post: work/horizontal/floor-framing/post.md
              - ‚óºÔ∏è Beam: work/horizontal/floor-framing/beam.md
              - ‚óºÔ∏è Joist: work/horizontal/floor-framing/joist.md
              - ‚óºÔ∏è Stair: work/horizontal/floor-framing/stair.md
              - ‚óºÔ∏è Subfloor Sheathing: work/horizontal/floor-framing/subfloor.md
              - üü™ Details: 
                  - ‚óºÔ∏è Rim Board: work/horizontal/floor-framing/details/rim.md
                  - ‚óºÔ∏è Ribbon Board: work/horizontal/floor-framing/details/ribbon.md
                  - ‚óºÔ∏è Blocking: work/horizontal/floor-framing/details/blocking.md
                  - ‚óºÔ∏è Blocking o.c.: work/horizontal/floor-framing/details/blockingoc.md
                  - ‚óºÔ∏è Bracing for drywall: work/horizontal/floor-framing/details/bracingdrywalls.md
                  - ‚óºÔ∏è Bolts: work/horizontal/floor-framing/details/bolts.md
                  - ‚óºÔ∏è Screws: work/horizontal/floor-framing/details/Screws.md
                  - ‚óºÔ∏è Steel Beam Web Fillers - Nailer Plates: work/horizontal/floor-framing/details/steelbeams.md
          - Roof Framing:
              - ‚óºÔ∏è Ridge: work/horizontal/roof-framing/ridge.md
              - ‚óºÔ∏è Header: work/horizontal/roof-framing/header.md
              - ‚óºÔ∏è Hip: work/horizontal/roof-framing/hip.md
              - ‚óºÔ∏è Valley: work/horizontal/roof-framing/valley.md
              - ‚óºÔ∏è Dormer: work/horizontal/roof-framing/dormer.md
              - ‚óºÔ∏è Overframes: work/horizontal/roof-framing/overframes.md
              - ‚óºÔ∏è Dbl Trpl Rafters: work/horizontal/roof-framing/dbl-trpl-rafters.md
              - ‚óºÔ∏è Canopy: work/horizontal/roof-framing/canopy.md
              - ‚óºÔ∏è Roof Sheathing: work/horizontal/roof-framing/roof-sheathing.md
      - Deck / Porch / Balcony:
          - ‚óºÔ∏è Railing: work/deck/railing.md
          - ‚óºÔ∏è Balcony Trims: work/deck/balcony-trims.md
          - ‚óºÔ∏è Anchor Bolts: work/deck/anchor-bolts.md

plugins:
  - search

markdown_extensions:
  - tables
  - attr_list
  - toc:
      permalink: true
